### PR TITLE
fix: typo in popup

### LINKED ISSUE #4: Popup has a typo
`you FREE` should say `your FREE`, instead.

### PR DESCRIPTION
**Pull request by hirehamir**
fixes #4.

### CODE REVIEW

**Review by hirehamir — COMMENTED** [review]
This pull request follows the suggestion in https://github.com/behnamazimi/merriam-webster-dictionary-extension/issues/4#issuecomment-1966628430.

**Comment by behnamazimi** [comment]
Thank you for dedicating your time to this.

**Comment by hirehamir** [comment]
You're welcome!

**Comment by hirehamir** [comment]
Thank you for making the code open source.

**Pull request merged**
